# Generated by Django 5.0.6 on 2024-05-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='活動標題')),
                ('host', models.CharField(max_length=20, verbose_name='活動主辦人')),
                ('description', models.TextField(max_length=200, verbose_name='活動簡介')),
                ('date', models.DateField(verbose_name='活動日期')),
            ],
            options={
                'verbose_name': '活動列表',
                'verbose_name_plural': '活動內容',
            },
        ),
    ]
