# Generated by Django 5.0.6 on 2024-05-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_content_icon_img_content_web_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='icon_img',
            field=models.ImageField(blank=True, upload_to='image/icon'),
        ),
    ]
