# Generated by Django 5.0.6 on 2024-05-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_content_icon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='background_image',
            field=models.ImageField(upload_to='background'),
        ),
        migrations.AlterField(
            model_name='content',
            name='icon_img',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
    ]
