# Generated by Django 5.0.6 on 2024-05-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_content_email_alter_content_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '村落資訊', 'verbose_name_plural': '活動內容'},
        ),
    ]
