# Generated by Django 5.0.6 on 2024-05-17 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_content_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '村落資訊', 'verbose_name_plural': '村落基本資訊'},
        ),
    ]
