# Generated by Django 5.0.6 on 2024-05-16 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='大標題')),
            ],
        ),
        migrations.CreateModel(
            name='DetailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='圖片')),
                ('image_description', models.CharField(blank=True, max_length=20, null=True, verbose_name='圖片簡介')),
                ('text', models.TextField(blank=True, null=True, verbose_name='內容段落')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='detail.post', verbose_name='新增段落')),
            ],
        ),
    ]
