# Generated by Django 5.0.6 on 2024-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_detailcontent_subtitle_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcontent',
            name='image_description_color',
            field=models.CharField(blank=True, default='#000000', help_text='請輸入十六進制顏色代碼，例如：#FF5733', max_length=7, null=True, verbose_name='(選填)圖片介紹字體顏色'),
        ),
        migrations.AddField(
            model_name='detailcontent',
            name='subTitle_color',
            field=models.CharField(blank=True, default='#000000', help_text='請輸入十六進制顏色代碼，例如：#FF5733', max_length=7, null=True, verbose_name='(選填)副標題字體顏色'),
        ),
        migrations.AlterField(
            model_name='detailcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='(選填)圖片'),
        ),
        migrations.AlterField(
            model_name='detailcontent',
            name='image_description',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='(選填)圖片簡介'),
        ),
        migrations.AlterField(
            model_name='detailcontent',
            name='subTitle',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='(選填)副標題'),
        ),
        migrations.AlterField(
            model_name='detailcontent',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='(選填)內容段落'),
        ),
    ]
