# Generated by Django 5.0.6 on 2024-05-16 12:49

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_detailcontent_image_description_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcontent',
            name='image_description_color',
            field=colorful.fields.RGBColorField(blank=True, default='#000000', help_text='請輸入十六進制顏色代碼，例如：#FF5733', null=True, verbose_name='(選填)圖片介紹字體顏色'),
        ),
        migrations.AlterField(
            model_name='detailcontent',
            name='subTitle_color',
            field=colorful.fields.RGBColorField(blank=True, default='#000000', help_text='請輸入十六進制顏色代碼，例如：#FF5733', null=True, verbose_name='(選填)副標題字體顏色'),
        ),
    ]
